// ! Do not edit this file directly, use npm run router instead

import { Outlet, Route, Routes } from 'react-router'

import DashLayout from '~app/-.../layout'
import Dash from '~app/-.../page'

import NotFound from '~components/common/NotFound'

function DashSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<DashLayout><Outlet /></DashLayout>}
      >
        <Route
          index
          element={<Dash />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default DashSubRouter
