// ! Do not edit this file directly, use npm run router instead

import { Outlet, Route, Routes } from 'react-router'

import Signout from '~app/signout.../page'

import NotFound from '~components/common/NotFound'

function SignoutSubRouter() {
  return (
    <Routes>
      <Route
        path=""
        element={<Outlet />}
      >
        <Route
          index
          element={<Signout />}
        />
        <Route
          path="*"
          element={<NotFound />}
        />
      </Route>
    </Routes>
  )
}

export default SignoutSubRouter
